#ifndef ERROR_H
#define ERROR_H

#define ERROR_LEXICAL 1
#define ERROR_SYNTAX 2
#define ERROR_SEMANTIC 3
#define ERROR_SEMANTIC_RUNTIME 4
#define ERROR_SEMANTIC_FUNCTION_CALL 5
#define ERROR_SEMANTIC_OTHER 6
#define ERROR_DIV_BY_NULL 9
#define ERROR_INTERNAL 99

#endif
